### ISSUE TITLE
Tester Output

### ISSUE THREAD

**Issue by jbennett23** [cs540-testers/HW3-Tester#2]
Tester V1.0
Elapsed time was: 0.16216s
Reference runtime is ~0.75s
See diff below. If you see nothing but the end message, you're good.
***
---
***************
*** 1,3 ****
--- 1,10 ----
+ # -*- coding: utf-8 -*-
+ """
+ Created on Sat Sep 26 08:59:39 2020
+
+ @author: juelb
+ """
+
Version: V1.0

succ([0, 1, 2], 0, 0)
***************
*** 43,50 ****
n_queens tests complete

n_queens_restart(7, 10, 0, 0)
! [0, 6, 4, 6, 1, 3, 5] - f=2
n_queens_restart(8, 1000, 0, 0)
! [0, 5, 7, 2, 6, 3, 1, 4] - f=0
! n_queens_restart tests complete
!
--- 50,89 ----
n_queens tests complete

n_queens_restart(7, 10, 0, 0)
! [0, 6, 1, 3, 5, 0, 4] - f=3
n_queens_restart(8, 1000, 0, 0)
! [0, 0, 7, 5, 2, 6, 1, 3] - f=2
! [0, 0, 7, 5, 2, 6, 1, 3] - f=2
! [0, 2, 0, 5, 7, 1, 3, 6] - f=2
! [0, 2, 4, 6, 1, 3, 5, 0] - f=2
! [0, 2, 4, 6, 1, 3, 5, 3] - f=2
! [0, 2, 4, 7, 0, 3, 1, 6] - f=2
! [0, 2, 5, 7, 4, 1, 3, 6] - f=2
! [0, 2, 6, 3, 7, 4, 1, 5] - f=2
! [0, 2, 6, 5, 7, 4, 1, 3] - f=2
! [0, 2, 7, 5, 3, 1, 4, 4] - f=2
! [0, 2, 7, 5, 3, 1, 4, 4] - f=2
! [0, 2, 7, 5, 3, 1, 6, 4] - f=2
! [0, 3, 1, 7, 1, 6, 2, 5] - f=2
! [0, 3, 4, 7, 1, 6, 2, 5] - f=2
! [0, 3, 5, 2, 6, 1, 7, 4] - f=2
! [0, 3, 5, 7, 1, 4, 2, 5] - f=2
! [0, 3, 6, 2, 5, 1, 1, 4] - f=2
! [0, 3, 6, 2, 5, 1, 1, 4] - f=2
! [0, 3, 6, 2, 7, 1, 4, 0] - f=2
! [0, 3, 6, 4, 1, 7, 5, 2] - f=2
! [0, 4, 1, 5, 2, 6, 3, 3] - f=2
! [0, 4, 1, 5, 2, 6, 3, 7] - f=2
! [0, 4, 2, 7, 5, 3, 1, 6] - f=2
! [0, 4, 6, 1, 5, 2, 0, 3] - f=2
! [0, 4, 6, 5, 3, 1, 7, 2] - f=2
! [0, 5, 1, 2, 6, 3, 7, 4] - f=2
! [0, 5, 3, 1, 6, 4, 2, 0] - f=2
! [0, 5, 3, 1, 7, 2, 2, 6] - f=2
! [0, 5, 7, 1, 3, 6, 2, 4] - f=2
! [0, 5, 7, 4, 1, 7, 2, 6] - f=2
! [0, 6, 1, 1, 5, 7, 2, 4] - f=2
! [0, 6, 3, 0, 2, 7, 5, 1] - f=2
! [0, 6, 3, 7, 2, 4, 5, 1] - f=2
! [0, 6, 4, 2, 7, 5, 3, 1] - f=2
! n_queens_restart tests complete
This is the end of the tester.

**Comment by jbennett23** [comment]
test.txt:

Version: V1.0

succ([0, 1, 2], 0, 0)
[[0, 0, 2], [0, 1, 1], [0, 2, 2]]
succ([1, 1, 2], 0, 0)
[]
succ tests complete

f([1, 2, 2])
3
f([2, 2, 2])
3
f([0, 0, 2])
3
f([0, 2, 0])
2
f([0, 2, 1])
2
f tests complete

choose_next([1, 1, 2], 1, 1)
[0, 1, 2]
choose_next([0, 2, 0], 0, 0)
[0, 2, 0]
choose_next([0, 1, 0], 0, 0)
[0, 2, 0]
choose_next([0, 1, 0], 0, 1)
None
choose_next tests complete

n_queens([0, 1, 2, 3, 5, 6, 6, 7], 1, 1)
[0, 1, 2, 3, 5, 6, 6, 7] - f=8
[0, 1, 2, 3, 5, 7, 6, 7] - f=7
[0, 1, 1, 3, 5, 7, 6, 7] - f=7
[0, 1, 1, 3, 5, 7, 6, 7]
n_queens([0, 7, 3, 4, 7, 1, 2, 2], 0, 0)
[0, 7, 3, 4, 7, 1, 2, 2] - f=7
[0, 6, 3, 4, 7, 1, 2, 2] - f=6
[0, 6, 3, 5, 7, 1, 2, 2] - f=4
[0, 6, 3, 5, 7, 1, 3, 2] - f=3
[0, 6, 3, 5, 7, 1, 4, 2] - f=0
[0, 6, 3, 5, 7, 1, 4, 2]
n_queens tests complete

n_queens_restart(7, 10, 0, 0)
[0, 6, 4, 6, 1, 3, 5] - f=2
n_queens_restart(8, 1000, 0, 0)
[0, 5, 7, 2, 6, 3, 1, 4] - f=0
n_queens_restart tests complete

**Comment by sauprankul** [comment]
a) not sure why you're printing that author information at the start. 

b) It looks like the only difference here is how you're generating random numbers. Are you calling seed()? Are you making sure to call randint() N-1 times per iteration of n_queens_restart? Comment with the first random state your code produces in nqr.

**Comment by haclark30** [comment]
Wasn't Stephen's output generated with random.seed(1) called at the beginning of n_queens_restart? We should probably update the README to reflect that.

**Comment by jbennett23** [comment]
> a) not sure why you're printing that author information at the start.
> 
> b) It looks like the only difference here is how you're generating random numbers. Are you calling seed()? Are you making sure to call randint() N-1 times per iteration of n_queens_restart? Comment with the first random state your code produces in nqr.

Before I was calling randint(0,n) so I changed that to randint(0, n-1). I commented out when I called seed(1).

for:  n_queens_restart(7, 10, 0, 0)
my first random state is:  [0, 1, 4, 6, 6, 6, 0]

for: n_queens_restart(8, 1000, 0, 0)
my first random state is: [0, 2, 1, 4, 1, 7, 7, 7]

**Comment by alexmoon01** [comment]
@jbennett23 Is this resolved?
